"""
Generated by rai-orm-from-text (CSDP) from examples/movie_catalog.orm.yaml.

For production use, set `implicit_properties: false` in raiconfig.yaml
to catch typos at definition time.
"""

from relationalai.semantics import Model, Integer, String

model = Model("movie_catalog")

# ---- Concepts (object types) ----
Movie = model.Concept("Movie", identify_by={"id": Integer})
Director = model.Concept("Director", identify_by={"name": String})

# ---- Enums ----
Rating = model.Enum("Rating", ["G", "PG", "PG-13", "R", "NC-17"])

# ---- Properties (binary fact types with uniqueness on the Movie role) ----
Movie.title = model.Property(f"{Movie} has title {String:title}")
Movie.director = model.Property(f"{Movie} directed by {Director:director}")
Movie.year = model.Property(f"{Movie} released in {Integer:year}")
Movie.rating = model.Property(f"{Movie} has rating {Rating:rating}")

# ---- Verbose-tier constraints ----

# Movie release year must be between 1888 (first known movie) and 2100 (catalog cap).
model.require((Movie.year >= 1888) & (Movie.year <= 2100))
