"""
Generated by rai-orm-from-schema from examples/movie_catalog.orm.yaml.

For production use, set `implicit_properties: false` in raiconfig.yaml
to catch typos at definition time. Without it, accessing an undeclared
property silently creates a new one — masking schema-recovery errors.
"""

from relationalai.semantics import Model, Integer, String

model = Model("movie_catalog")

# ---- Concepts (object types) ----
Director = model.Concept("Director", identify_by={"id": Integer})
Actor = model.Concept("Actor", identify_by={"id": Integer})
Movie = model.Concept("Movie", identify_by={"id": Integer})

# Objectified m:n binary — composite identity from the underlying roles
MovieActor = model.Concept("MovieActor", identify_by={"movie": Movie, "actor": Actor})

# ---- Enums ----
Rating = model.Enum("Rating", ["G", "PG", "PG-13", "R", "NC-17"])

# ---- Properties (binary fact types with uniqueness on one role) ----
Director.name = model.Property(f"{Director} has name {String:name}")
Actor.name = model.Property(f"{Actor} has name {String:name}")

Movie.title = model.Property(f"{Movie} has title {String:title}")
Movie.release_year = model.Property(f"{Movie} was released in {Integer:year}")
Movie.rating = model.Property(f"{Movie} has rating {Rating:rating}")
Movie.director = model.Property(f"{Movie} directed by {Director:director}")

MovieActor.character_name = model.Property(
    f"{MovieActor} plays character {String:characterName}"
)

# ---- Verbose-tier constraints ----

# Movie release year must be between 1888 and 2100 (from CHECK constraint)
model.require((Movie.release_year >= 1888) & (Movie.release_year <= 2100))

# Director.name and Actor.name are unique (from UNIQUE constraint).
# Property semantics already enforce single-valuedness on the entity side;
# the value-side uniqueness is the additional 1:1 enforcement.
model.require(Director.name.is_unique())
model.require(Actor.name.is_unique())
